import {
  ResumeSectionKey,
  ResumeTemplateConfig,
  ResumeTemplateId,
  ResumeTemplateLayout,
  ResumeTemplateTheme,
  ResumeTemplateThemeOverrides,
} from "./types";

export const RESUME_FONT_OPTIONS = [
  "Arial, sans-serif",
  "'Helvetica Neue', Arial, sans-serif",
  "Georgia, serif",
  "'Times New Roman', serif",
  "'Trebuchet MS', sans-serif",
  "Verdana, sans-serif",
] as const;

const DEFAULT_HEADINGS: Record<ResumeSectionKey, string> = {
  summary: "Summary",
  skills: "Skills",
  experience: "Experience",
  projects: "Projects",
  education: "Education",
  certifications: "Certifications",
  languages: "Languages",
  personal: "Personal Details",
  additional: "",
  references: "References",
};

// The five modern templates share one structure and differ only in look.
const modernLayout = (
  overrides: Partial<ResumeTemplateLayout>
): ResumeTemplateLayout => ({
  page: "a4",
  header: "left",
  headerRule: false,
  nameCase: "normal",
  contact: "icons",
  heading: "rule",
  headingTone: "heading",
  entry: "standard",
  dates: "standard",
  languages: "inline",
  photo: "none",
  sections: [
    "summary",
    "skills",
    "experience",
    "projects",
    "education",
    "certifications",
    "languages",
    "additional",
    "references",
  ],
  headings: DEFAULT_HEADINGS,
  headerDetails: [],
  sectionDetails: [],
  referencesFallback: "",
  ...overrides,
});

export const RESUME_TEMPLATE_CONFIGS: ResumeTemplateConfig[] = [
  // ---- Regional formats ----------------------------------------------------
  {
    id: "us-standard",
    label: "US Resume",
    group: "regional",
    description:
      "US conventions: Letter size, one column, no photo, date of birth or personal details. Summary and skills lead, then reverse-chronological experience. References are left off.",
    layout: {
      page: "letter",
      header: "center",
      headerRule: false,
      nameCase: "normal",
      contact: "inline",
      heading: "rule",
      headingTone: "heading",
      entry: "standard",
      dates: "standard",
      languages: "inline",
      photo: "none",
      sections: [
        "summary",
        "skills",
        "experience",
        "education",
        "certifications",
        "projects",
        "languages",
        "additional",
        "references",
      ],
      headings: {
        ...DEFAULT_HEADINGS,
        summary: "Professional Summary",
        experience: "Professional Experience",
      },
      headerDetails: [{ field: "workAuthorization", label: "Work Authorization" }],
      sectionDetails: [],
      referencesFallback: "",
    },
    defaults: {
      accent: "#1f3a5f",
      mutedAccent: "#dbe3ee",
      headingColor: "#111827",
      bodyColor: "#1f2937",
      fontFamily: "Arial, sans-serif",
      showPhoto: false,
      baseFontSize: 14,
      lineHeight: 1.45,
      sectionSpacing: 16,
    },
  },
  {
    id: "uk-cv",
    label: "UK CV",
    group: "regional",
    description:
      "UK conventions: A4, no photo, date of birth, nationality or marital status. Opens with a personal profile and key skills, lists employment history, and closes with references available on request.",
    layout: {
      page: "a4",
      header: "left",
      headerRule: true,
      nameCase: "normal",
      contact: "inline",
      heading: "caps",
      headingTone: "accent",
      entry: "standard",
      dates: "standard",
      languages: "inline",
      photo: "none",
      sections: [
        "summary",
        "skills",
        "experience",
        "education",
        "certifications",
        "projects",
        "languages",
        "additional",
        "personal",
        "references",
      ],
      headings: {
        ...DEFAULT_HEADINGS,
        summary: "Personal Profile",
        skills: "Key Skills",
        experience: "Employment History",
        certifications: "Certifications & Training",
        personal: "Additional Information",
      },
      headerDetails: [],
      sectionDetails: [
        { field: "workAuthorization", label: "Right to work" },
        { field: "drivingLicence", label: "Driving licence" },
      ],
      referencesFallback: "References available on request.",
    },
    defaults: {
      accent: "#0f4c5c",
      mutedAccent: "#d5e5e8",
      headingColor: "#0f172a",
      bodyColor: "#1e293b",
      fontFamily: "Arial, sans-serif",
      showPhoto: false,
      baseFontSize: 14,
      lineHeight: 1.45,
      sectionSpacing: 16,
    },
  },
  {
    id: "australian",
    label: "Australian Resume",
    group: "regional",
    description:
      "Australian conventions: A4, no photo or date of birth, work rights stated up front. Career summary and key skills, detailed employment history, licences, and referees.",
    layout: {
      page: "a4",
      header: "left",
      headerRule: true,
      nameCase: "normal",
      contact: "inline",
      heading: "bar",
      headingTone: "heading",
      entry: "standard",
      dates: "standard",
      languages: "inline",
      photo: "none",
      sections: [
        "summary",
        "skills",
        "experience",
        "education",
        "certifications",
        "projects",
        "languages",
        "additional",
        "references",
      ],
      headings: {
        ...DEFAULT_HEADINGS,
        summary: "Career Summary",
        skills: "Key Skills",
        experience: "Employment History",
        education: "Education & Qualifications",
        certifications: "Licences & Certifications",
        references: "Referees",
      },
      headerDetails: [
        { field: "workAuthorization", label: "Work rights" },
        { field: "drivingLicence", label: "Driver's licence" },
      ],
      sectionDetails: [],
      referencesFallback: "Referees available upon request.",
    },
    defaults: {
      accent: "#1d5c4d",
      mutedAccent: "#d7e8e2",
      headingColor: "#0f172a",
      bodyColor: "#1f2937",
      fontFamily: "Arial, sans-serif",
      showPhoto: false,
      baseFontSize: 14,
      lineHeight: 1.45,
      sectionSpacing: 16,
    },
  },
  {
    id: "europass",
    label: "Europass CV",
    group: "regional",
    description:
      "European (Europass) structure: A4, optional photo, labelled personal information, then About me, Work experience, Education and training, and Language skills on the CEFR scale.",
    layout: {
      page: "a4",
      header: "europass",
      headerRule: true,
      nameCase: "normal",
      contact: "labelled",
      heading: "line",
      headingTone: "accent",
      entry: "europass",
      dates: "europass",
      languages: "europass",
      photo: "left",
      sections: [
        "summary",
        "experience",
        "education",
        "languages",
        "skills",
        "certifications",
        "projects",
        "personal",
        "additional",
        "references",
      ],
      headings: {
        ...DEFAULT_HEADINGS,
        summary: "About Me",
        experience: "Work Experience",
        education: "Education and Training",
        languages: "Language Skills",
        personal: "Driving Licence",
      },
      headerDetails: [
        { field: "dateOfBirth", label: "Date of birth" },
        { field: "nationality", label: "Nationality" },
        { field: "gender", label: "Gender" },
        { field: "workAuthorization", label: "Work permit" },
      ],
      sectionDetails: [{ field: "drivingLicence", label: "Driving Licence" }],
      referencesFallback: "",
    },
    defaults: {
      accent: "#0b4d95",
      mutedAccent: "#dce6f3",
      headingColor: "#0f172a",
      bodyColor: "#1f2937",
      fontFamily: "Arial, sans-serif",
      showPhoto: true,
      baseFontSize: 14,
      lineHeight: 1.45,
      sectionSpacing: 16,
    },
  },
  {
    id: "middle-east",
    label: "Middle East CV",
    group: "regional",
    description:
      "Gulf & Middle East conventions: A4, professional photo, and a personal details block (nationality, date of birth, marital and visa status, driving licence). Languages and references included.",
    layout: {
      page: "a4",
      header: "split",
      headerRule: true,
      nameCase: "normal",
      contact: "inline",
      heading: "rule",
      headingTone: "accent",
      entry: "standard",
      dates: "standard",
      languages: "inline",
      photo: "right",
      sections: [
        "summary",
        "personal",
        "skills",
        "experience",
        "education",
        "certifications",
        "projects",
        "languages",
        "additional",
        "references",
      ],
      headings: {
        ...DEFAULT_HEADINGS,
        summary: "Professional Summary",
        skills: "Core Competencies",
        experience: "Professional Experience",
        personal: "Personal Details",
      },
      headerDetails: [],
      sectionDetails: [
        { field: "nationality", label: "Nationality" },
        { field: "dateOfBirth", label: "Date of Birth" },
        { field: "gender", label: "Gender" },
        { field: "maritalStatus", label: "Marital Status" },
        { field: "workAuthorization", label: "Visa Status" },
        { field: "drivingLicence", label: "Driving Licence" },
      ],
      referencesFallback: "Available upon request.",
    },
    defaults: {
      accent: "#7a5412",
      mutedAccent: "#efe4cf",
      headingColor: "#111827",
      bodyColor: "#1f2937",
      fontFamily: "Arial, sans-serif",
      showPhoto: true,
      baseFontSize: 14,
      lineHeight: 1.45,
      sectionSpacing: 16,
    },
  },

  // ---- Modern ----------------------------------------------------------------
  {
    id: "classic-blue",
    label: "Meridian",
    group: "modern",
    description: "Crisp single column with blue section rules and a clear hierarchy.",
    layout: modernLayout({ headingTone: "accent" }),
    defaults: {
      accent: "#2563eb",
      mutedAccent: "#dbeafe",
      headingColor: "#0f172a",
      bodyColor: "#334155",
      fontFamily: "Arial, sans-serif",
      showPhoto: false,
      baseFontSize: 13,
      lineHeight: 1.5,
      sectionSpacing: 16,
    },
  },
  {
    id: "bold-modern",
    label: "Onyx",
    group: "modern",
    description: "High-contrast black typography with a strong name and bold section bars.",
    layout: modernLayout({ headerRule: true, heading: "bar" }),
    defaults: {
      accent: "#111827",
      mutedAccent: "#e5e7eb",
      headingColor: "#111827",
      bodyColor: "#374151",
      fontFamily: "'Helvetica Neue', Arial, sans-serif",
      showPhoto: false,
      baseFontSize: 13,
      lineHeight: 1.5,
      sectionSpacing: 16,
    },
  },
  {
    id: "analyst-photo",
    label: "Portrait",
    group: "modern",
    description: "Structured layout with an optional profile photo beside your name.",
    layout: modernLayout({ header: "split", headerRule: true, photo: "right", headingTone: "accent" }),
    defaults: {
      accent: "#1d4ed8",
      mutedAccent: "#dbeafe",
      headingColor: "#1e3a8a",
      bodyColor: "#334155",
      fontFamily: "Arial, sans-serif",
      showPhoto: true,
      baseFontSize: 13,
      lineHeight: 1.5,
      sectionSpacing: 16,
    },
  },
  {
    id: "minimal-slate",
    label: "Linear",
    group: "modern",
    description: "Pared-back and text-only — the safest pick for strict applicant tracking systems.",
    layout: modernLayout({ contact: "inline", heading: "caps", headingTone: "accent" }),
    defaults: {
      accent: "#475569",
      mutedAccent: "#e2e8f0",
      headingColor: "#0f172a",
      bodyColor: "#334155",
      fontFamily: "Verdana, sans-serif",
      showPhoto: false,
      baseFontSize: 12,
      lineHeight: 1.55,
      sectionSpacing: 16,
    },
  },
  {
    id: "executive-serif",
    label: "Sterling",
    group: "modern",
    description: "Refined serif with a centred header, suited to senior and traditional roles.",
    layout: modernLayout({
      header: "center",
      nameCase: "upper",
      contact: "inline",
      heading: "centered",
      headingTone: "accent",
    }),
    defaults: {
      accent: "#7c2d12",
      mutedAccent: "#f1e2d6",
      headingColor: "#1c1917",
      bodyColor: "#3f3a36",
      fontFamily: "Georgia, serif",
      showPhoto: false,
      baseFontSize: 13,
      lineHeight: 1.55,
      sectionSpacing: 18,
    },
  },
];

export const getResumeTemplateConfig = (templateId: ResumeTemplateId) =>
  RESUME_TEMPLATE_CONFIGS.find((template) => template.id === templateId) ||
  RESUME_TEMPLATE_CONFIGS.find((template) => template.id === "classic-blue") ||
  RESUME_TEMPLATE_CONFIGS[0];

const normalizeColor = (value: string, fallback: string) =>
  /^#[0-9a-f]{6}$/i.test(value || "") ? value : fallback;

export const resolveResumeTemplateTheme = (
  templateId: ResumeTemplateId,
  overrides: ResumeTemplateThemeOverrides = {}
): ResumeTemplateTheme => {
  const template = getResumeTemplateConfig(templateId);
  const theme = { ...template.defaults, ...overrides };

  return {
    ...theme,
    accent: normalizeColor(theme.accent, template.defaults.accent),
    mutedAccent: normalizeColor(theme.mutedAccent, template.defaults.mutedAccent),
    headingColor: normalizeColor(theme.headingColor, template.defaults.headingColor),
    bodyColor: normalizeColor(theme.bodyColor, template.defaults.bodyColor),
    baseFontSize: Math.max(11, Math.min(15, Number(theme.baseFontSize) || template.defaults.baseFontSize)),
    lineHeight: Math.max(1.35, Math.min(1.95, Number(theme.lineHeight) || template.defaults.lineHeight)),
    sectionSpacing: Math.max(10, Math.min(24, Number(theme.sectionSpacing) || template.defaults.sectionSpacing)),
  };
};
