import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sample Resume Template",
  description:
    "Preview a clean, ATS-friendly resume template generated by SynCV.",
  robots: {
    index: false,
    follow: false,
  },
};

export default function StaticTemplateLayout({ children }: { children: React.ReactNode }) {
  return children;
}
